#配置端口号
server:
  port: 8087

spring:
  application:
    #配置服务名
    name: flowable-ui
  profiles:
    active: sit
  #Druid 连接池通用配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select count(1) from sys.objects Where type='U' And type_desc='USER_TABLE'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat # wall 若开启 wall，会把 if 中的 and 判断为注入进行拦截
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#配置xml映射
mybatis:
  # 新增 modeler-mybatis-mappings xml 扫描
  mapper-locations: mapper/*/*.xml, classpath*:mapper/*.xml, classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 参数配置
  configuration-properties:
    # 配置流程引擎参数，详情可见 DatabaseConfiguration
    blobType: BLOB
    boolValue: TRUE
    # 不要设置库名，否则会出现双库名 bug
    prefix: ''
#pageHelper 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

# flowable 配置
flowable:
  # 关闭异步，不关闭历史数据的插入就是异步的，会在同一个事物里面，无法回滚
  # 开发可开启会提高些效率，上线需要关闭
  async-executor-activate: false
  #database-schema-update: true


---
#本地/测试服配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable_ui?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username : root
    password : GmOehtizWnxVGw0bjgKnitxlHbNwjaEYSN6k64jtnRErmjhPbD+KifBKL2RIho7aejbSL1Qdb3ghGiZU/E0Wlg==
    driver-class-name: com.mysql.jdbc.Driver
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKcIpQrk+z1i5fbrssFelC0UOuKDc5MDq/tGetwgX4TBDCnxUx2YMzMjq1DKiQvrJRTmrt4T/9Ya9IRCkvWn36kCAwEAAQ==
  #  #Redis配置
#  redis:
#    host: xxxx #redis 地址
#    password: xxxx
#    port: 6379
#    sentinel:
#      master: mymaster
#      nodes: xxxx,xxxx #redis 多节点地址
#    lettuce:
#      pool:
#        min-idle: 0
#        max-idle: 8
#        max-wait: -1ms
#        max-active: 8
#      shutdown-timeout: 100ms




  #Redis配置
#  redis:
#    lettuce:
#      pool:
#        min-idle: 0
#        max-idle: 8
#        max-wait: -1ms
#        max-active: 8
#      shutdown-timeout: 100ms
#    cluster:
#      nodes: xxxx,xxxx #redis 多节点地址

